import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from "axios";
import React  from 'react';
import InventoryTable from "../src/components/InventoryTable";
import SignIn from "../src/components/SignIn";
import CreateUser from "../src/components/CreateUser";
import { Spinner} from "@chakra-ui/react"


export default function Home() {

  const [inventoryData, setInventoryData] = React.useState([])
  const [update, setUpdate] = React.useState(true)
  const [authd, setAuthd] = React.useState(false)
  const [master, setMaster] = React.useState(false)
  const [loading, setLoading] = React.useState(false)

  const refresh = () => {
    setUpdate(!update)
  }

  React.useEffect(async () => {
    const response = await axios.get(`/api/inventory`);
    setInventoryData(response.data)
  }, [update]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Plants Direct</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/plant.png" />
      </Head>

      <main className={styles.main}>
        {loading ? <Spinner size="xl" /> :
        authd ? 
        <div style={{display:'flex' , flexDirection: 'column', alignItems:'center', gap:'10px'}}>
          <InventoryTable data={inventoryData} refresh={refresh} setLoading={setLoading}/>
          {master && <CreateUser setLoading={setLoading}/> }
        </div>
         : 
        <>
          <SignIn setAuthd={setAuthd} setLoading={setLoading} setMaster={setMaster}/>
        </>
        }
      </main>
    </div>
  )
}
